DROP SCHEMA IF EXISTS db_dogtor_prd;

CREATE SCHEMA db_dogtor_prd;

USE db_dogtor_prd;

/* DROP ALL TABLES */
DROP TABLE IF EXISTS tb_user;

DROP TABLE IF EXISTS tb_address;

/* CREATE TABLES */
/* CREATE TABLE USER */
CREATE TABLE tb_user (
    user_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_uuid VARCHAR(36) NOT NULL,
    --
    full_name VARCHAR(45) NOT NULL,
    hash_cpf VARCHAR(40) NOT NULL,
    email VARCHAR(45) NOT NULL,
    birth_date VARCHAR(45) NOT NULL,
    hash_password VARCHAR(255) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE ADDRESS */
CREATE TABLE tb_address (
    address_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    --
    user_uuid VARCHAR(36),
    company_branch_uuid VARCHAR(36),
    zip_code VARCHAR(45) NOT NULL,
    country VARCHAR(45) NOT NULL,
    city VARCHAR(45) NOT NULL,
    street_name VARCHAR(255) NOT NULL,
    number INT NOT NULL,
    additional_info LONGTEXT NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE CARD INFO */
CREATE TABLE tb_card_info (
    card_info_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    card_info_uuid VARCHAR(36) NOT NULL,
    --
    user_uuid VARCHAR(36) NOT NULL,
    hash_cpf VARCHAR(40) NOT NULL,
    card_number VARCHAR(45) NOT NULL,
    card_expire_date VARCHAR(5) NOT NULL,
    card_flag VARCHAR(45) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE BANK INFO */
CREATE TABLE tb_bank_info (
    bank_info_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    bank_info_uuid VARCHAR(36) NOT NULL,
    --
    document VARCHAR(45) NOT NULL,
    bank_number VARCHAR(45) NOT NULL,
    agency VARCHAR(45) NOT NULL,
    agency_digit VARCHAR(45) NOT NULL,
    account_number VARCHAR(45) NOT NULL,
    account_number_digit VARCHAR(45) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE PAYMENT */
CREATE TABLE tb_payment (
    payment_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    payment_uuid VARCHAR(36) NOT NULL,
    --
    payment_method VARCHAR(45) NOT NULL,
    installments INT NOT NULL,
    installment_due_date INT NOT NULL,
    bill_total DECIMAL(10, 2) NOT NULL,
    doctor_uuid VARCHAR(36) NOT NULL,
    pet_uuid VARCHAR(36) NOT NULL,
    user_uuid VARCHAR(36) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE PET */
CREATE TABLE tb_pet(
    pet_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    pet_uuid VARCHAR(36) NOT NULL,
    --
    user_id INT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    birth_date TIMESTAMP NOT NULL,
    size DECIMAL(10, 2) NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    description LONGTEXT NOT NULL,
    specie_id INT NOT NULL,
    race_id INT NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE SPECIES */
CREATE TABLE tb_species (
    specie_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    --
    specie VARCHAR(255) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE RACES */
CREATE TABLE tb_races (
    race_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    --
    race VARCHAR(255) NOT NULL,
    specie_id INT NOT NULL,
    -- 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE COMPANY */
CREATE TABLE tb_company (
    company_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    company_uuid VARCHAR(36) NOT NULL,
    --
    document VARCHAR(45) NOT NULL,
    corporate_name VARCHAR(45) NOT NULL,
    social_name VARCHAR(45) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_number VARCHAR(45) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE COMPANY BRANCH */
CREATE TABLE tb_company_branch (
    company_branch_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    company_branch_uuid VARCHAR(36) NOT NULL,
    --
    company_uuid VARCHAR(36) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_number VARCHAR(45) NOT NULL,
    bank_info_uuid VARCHAR(36) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE DOCTOR */
CREATE TABLE tb_doctor (
    doctor_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    doctor_uuid VARCHAR(36) NOT NULL,
    --
    full_name VARCHAR(255) NOT NULL,
    birth_date VARCHAR(45) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_number VARCHAR(45) NOT NULL,
    expertise VARCHAR(255) NOT NULL,
    description LONGTEXT NOT NULL,
    company_branch_uuid VARCHAR(36) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE SERVICES */
CREATE TABLE tb_services (
    services_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    services_uuid VARCHAR(36) NOT NULL,
    --
    name VARCHAR(255) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE DOCTOR SERVICES */
CREATE TABLE tb_doctor_services (
    doctor_services_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    doctor_services_uuid VARCHAR(36) NOT NULL,
    --
    doctor_uuid VARCHAR(36) NOT NULL,
    service_id INT NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE AVAILABILLITY */
CREATE TABLE tb_availabillity (
    availabillity_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    availabillity_uuid VARCHAR(36) NOT NULL,
    --
    doctor_service_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    appointment_id INT NOT NULL,
    available BOOLEAN NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE APPOINTMENT */
CREATE TABLE tb_appointment (
    availabillity_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    availabillity_uuid VARCHAR(36) NOT NULL,
    --
    pet_uuid VARCHAR(36) NOT NULL,
    doctor_uuid VARCHAR(36) NOT NULL,
    notification_uuid VARCHAR(36) NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

/* CREATE TABLE NOTIFICATION */
CREATE TABLE tb_notification (
    notification_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    notification_uuid VARCHAR(36) NOT NULL,
    --
    company_uuid VARCHAR(36) NOT NULL,
    info LONGTEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    delivered BOOLEAN NOT NULL,
    --
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);