INSERT INTO tb_species (specie) VALUES ("dog");

INSERT INTO tb_races (race, specie_id) VALUES ("Afador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afaird", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affen Border Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affen Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affen Tzu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenchon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affengriffon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenhuahua", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenpinscher", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenpoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenpug", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenshire", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Affenwich", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afghan Chon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afghan Collie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afghan Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afghan Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afghan Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afghan Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Afollie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Airedale Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Airedale Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Airedoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akbash", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akbash Pyrenees", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akbash Rottie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aki-poo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akita", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akita Basset", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akita Bernard", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akita Chow", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akita Pit", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akita Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Akitamatian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Goldenmute", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Husky Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Irish Setsky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Klee Kai", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Malador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Malamute", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Pit Bull Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alaskan Weimsky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Alusky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bandogge", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Boston Bull Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Boxer Foxhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bull-Aussie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bull Dane", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bull Dogue De Bordeaux", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bull-Jack", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bull Pei", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bull Staffy", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bulldog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bulldog Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bullhuahua", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Bullweiler", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Chow Bulldog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Eagle Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American English Coonhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Eskimo Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Foxeagle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Foxhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Foxy Dane", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American French Bull Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Hairless Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Lab Foxhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Leopard Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Molossus", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Pit Bull Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Pit Corso", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Pugabull", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Rat Pinscher", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Staffordshire Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("American Water Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Amstiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Anatolian Pyrenees", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Anatolian Shepherd Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Appenzeller Sennenhunde", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Auggie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aussalier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aussie-Chi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aussie Rottie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aussie Shiba", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aussiedoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Aussiepom", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Bernedoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Boxherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Cattle Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Kelpie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Labradoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Shepherd Husky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Shepherd Lab Mix", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Shepherd Pit Bull Mix", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Stumpy Tail Cattle Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Australian Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Azawakh", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Ba-Shar", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bagle Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Barbado da Terceira", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Barbet", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bascottie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basenji", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bassador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basschshund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basset Bleu de Gascogne", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basset Fauve de Bretagne", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basset Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basset Jack", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Basset Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bassetoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bavarian Mountain Scent Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bea-Tzu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Beabull", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Beagle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Beaglier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bearded Collie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bedlington Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Belgian Laekenois", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Belgian Malinois", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Belgian Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Belgian Tervuren", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bergamasco Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Berger Picard", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bernedoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bernese Mountain Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bichon Frise", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bichonaranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bidoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Biewer Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Black and Tan Coonhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Black Mouth Cur", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Black Russian Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bloodhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Blue Lacy", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bluetick Coonhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bocker", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boerboel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boglen Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bohemian Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bolognese", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bolonoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Borador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Border-Aussie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Border Collie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Border Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Border Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bordoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Borzoi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("BoShih", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bossie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boston Boxer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boston Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boston Terrier Pekingese Mix", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bouvier des Flandres", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boxador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boxer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boxerdoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boxmatian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boxweiler", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Boykin Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bracco Italiano", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Braque du Bourbonnais", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Braque Francais Pyrenean", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Briard", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Brittany", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Broholmer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Brusselranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Brussels Griffon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bugg", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bull Arab", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bull-Pei", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bull Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bullador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bullboxer Pit", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bulldog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bullmastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Bullmatian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cairn Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cairnoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Canaan Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cane Corso", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cardigan Welsh Corgi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Carolina Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Catahoula Bulldog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Catahoula Leopard Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Caucasian Shepherd Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cav-a-Jack", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cav-a-Malt", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cava-Chin", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cava Inu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cava-lon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cavachon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cavador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cavalier King Charles Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cavapom", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cavapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Central Asian Shepherd Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cesky Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chabrador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cheagle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chesapeake Bay Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chi Chi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chi-Poo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chigi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chihuahua", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chilier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chinaranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chinese Crested", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chinese Shar-Pei", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chinook", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chion", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chipin", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chipoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chiweenie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chorkie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chow Chow", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chow Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chug", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Chusky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cirneco dell’Etna", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Clumber Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cockalier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cockapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cockapoochi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cocker Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Cockeranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Collie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Corgi Inu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Corgidor", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Corgipoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Corkie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Corman Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Coton de Tulear", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Croatian Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Curly-Coated Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Czechoslovakian Vlcak", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dachsador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dachshund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dalmatian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dameranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dandie Dinmont Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Daniff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Danish-Swedish Farmdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Deutscher Wachtelhund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Doberdor", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Doberman Pinscher", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Docker", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dogo Argentino", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dogue de Bordeaux", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dorgi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dorkie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Doxiepoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Doxle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Drentsche Patrijshond", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Drever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Dutch Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("English Cocker Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("English Foxhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("English Setter", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("English Springer Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("English Toy Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Entlebucher Mountain Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Eskipoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Estrela Mountain Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Eurasier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Field Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Fila Brasileiro", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Finnish Lapphund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Finnish Spitz", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Flat-Coated Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Fox Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("French Bulldog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("French Bullhuahua", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("French Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Frenchton", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Frengle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Longhaired Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Pinscher", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Shepherd Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Shepherd Pit Bull", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Shepherd Rottweiler Mix", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Sheprador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Shorthaired Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Spitz", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("German Wirehaired Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Giant Schnauzer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Glen of Imaal Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Goberian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Goldador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Cavalier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Cocker Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Mountain Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Mountain Doodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Retriever Corgi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Golden Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Goldendoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Gollie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Gordon Setter", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Great Dane", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Great Pyrenees", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Greater Swiss Mountain Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Greyador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Greyhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Hamiltonstovare", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Hanoverian Scenthound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Harrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Havanese", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Havapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Hokkaido", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Horgi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Hovawart", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Huskita", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Huskydoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Ibizan Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Icelandic Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Irish Red And White Setter", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Irish Setter", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Irish Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Irish Water Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Irish Wolfhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Italian Greyhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jack-A-Poo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jack Chi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jack Russell Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jackabee", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jackaranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jackshund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Jagdterrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Japanese Chin", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Japanese Spitz", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Korean Jindo Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kai Ken", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kangal Shepherd Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Karelian Bear Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Keeshond", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kerry Blue Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("King Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kishu Ken", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Komondor", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kooikerhondje", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kromfohrlander", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kuvasz", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Kyi-Leo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("La Pom", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lab Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labernese", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labmaraner", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labrabull", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labradane", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labradoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labrador Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labrastaff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Labsky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lagotto Romagnolo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lakeland Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lancashire Heeler", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lapponian Herder", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Leonberger", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lhasa Apso", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lhasapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Lowchen", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Maltese", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Maltese Shih Tzu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Maltipoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Manchester Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Maremma Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mastador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mauzer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Meagle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Miniature Pinscher", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Miniature Schnauzer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Morkie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mountain Cur", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mountain Feist", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mudi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Mutt (Mixed)", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Neapolitan Mastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Newfoundland", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Newfypoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Norfolk Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Northern Inuit Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Norwegian Buhund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Norwegian Elkhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Norwegian Lundehund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Norwich Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Nova Scotia Duck Tolling Retriever", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Old English Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Otterhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Papillon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Papipoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Patterdale Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Peekapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pekalier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pekingese", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pembroke Welsh Corgi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Perro de Presa Canario", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Petit Basset Griffon Vendéen", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pharaoh Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pitsky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Plott", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pocket Beagle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Polish Lowland Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomanauze", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomchi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomeagle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomeranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomeranian Cockapoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomerdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pomsky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Poochon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Poodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Poogle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Porcelaine", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Porkie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Portuguese Podengo Pequeno", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Portuguese Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Portuguese Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Portuguese Water Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pudelpointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pug", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pugalier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Puggat", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Puggle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Puginese", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Puli", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pyredoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pyrenean Mastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Pyrenean Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Rafeiro do Alentejo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Rat Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Redbone Coonhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Rhodesian Ridgeback", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Romanian Mioritic Shepherd Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Rottador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Rottle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Rottweiler", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Russian Toy", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Russian Tsvetnaya Bolonka", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Saint Berdoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Saint Bernard", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Saluki", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Samoyed", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Samusky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Schapendoes", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Schipperke", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Schnocker", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Schnoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Scoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Scottish Deerhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Scottish Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Sealyham Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Segugio Italiano", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Sheepadoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shepadoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shepsky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shetland Sheepdog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shiba Inu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shichon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shih-Poo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shih Tzu", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shikoku", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shiloh Shepherd", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shiranian", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shollie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Shorkie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Siberian Husky", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Silken Windhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Silky Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Skye Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Sloughi", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Slovakian Wirehaired Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Slovensky Cuvac", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Slovensky Kopov", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Small Munsterlander Pointer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Soft Coated Wheaten Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Spanish Mastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Spanish Water Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Spinone Italiano", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Springador", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Springerdoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Stabyhoun", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Staffordshire Bull Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Staffy Bull Bullmastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Standard Schnauzer", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Sussex Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Swedish Lapphund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Swedish Vallhund", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Taiwan Dog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Terripoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Texas Heeler", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Thai Ridgeback", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Tibetan Mastiff", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Tibetan Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Tibetan Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Tornjak", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Tosa", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Toy Fox Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Transylvanian Hound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Treeing Tennessee Brindle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Treeing Walker Coonhound", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Utonagan", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Valley Bulldog", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Vizsla", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Weimaraner", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Weimardoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Welsh Springer Spaniel", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Welsh Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("West Highland White Terrier", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Westiepoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Whippet", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Whoodle", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Wirehaired Pointing Griffon", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Working Kelpie", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Xoloitzcuintli", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Yakutian Laika", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Yorkipoo", 1);
INSERT INTO tb_races (race, specie_id) VALUES ("Yorkshire Terrier", 1);
